package com.vaadHL.example.jpa;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainDes extends VerticalLayout {
	protected VerticalLayout laL001;
	protected Label _b_A__b_4;
	protected CheckBox chkReadOnly;
	protected ComboBox cbChoosingMode;
	protected Label lbCustomization;
	protected VerticalLayout laCustNCM;
	protected CheckBox chkDetails;
	protected CheckBox chkAddRec;
	protected CheckBox chkDeleteRec;
	protected CheckBox chkEditRec;
	protected CheckBox chkViewRec;
	protected ComboBox cbDoubleClick;
	protected VerticalLayout laCustChM;
	protected CheckBox chkDetailsChM;
	protected CheckBox chkAddRecChM;
	protected CheckBox chkDeleteRecChM;
	protected CheckBox chkEditRecChM;
	protected CheckBox chkViewRecChM;
	protected ComboBox cbDoubleClickChM;
	protected TextArea taChoosed;
	protected VerticalLayout laM001;
	protected Label _b_A__b_;
	protected CheckBox chkAskSave;
	protected CheckBox chkAskDiscard;
	protected CheckBox chkAskDelete;
	protected CheckBox chkAskCreate;
	protected CheckBox chkPrevNext;
	protected ComboBox cbAutoSaveDiscard;
	protected ComboBox cbClosingMethod;
	protected VerticalLayout laPermissions;
	protected Label _b_A__b_5;
	protected Table tPerm;
	protected Button btRunTest;
	protected Button btExit;
	protected Label lbDemoVer;
	protected Label lbHLVer;
	protected Label lbVaadVer;

	public MainDes() {
		Design.read(this);
	}
}
